ansh_dbt_youtube:
  outputs:
    dev:
      catalog: dbt_tutorial_dev
      host: dbc-e38c62a0-ecaa.cloud.databricks.com
      http_path: /sql/1.0/warehouses/71452343b06c1f69
      schema: default
      threads: 1
      token: YOUR_DATABRICKS_TOKEN
      type: databricks
  target: dev
